### ISSUE TITLE
Windows 11 - Block WHEA from Event Log (Information)

### ISSUE THREAD

**Issue by hahagu** [mann1x/WHEAService#2]
You can manually disable an error source from being auto logged to the event viewer,
by editing [Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\WMI\Autologger\EventLog-System\{GUID}]
and setting `Enabled` key to `0`.
This does not only apply to Windows 11, and is applicable from Windows 7+, from what I know.
Also, I believe this also does not disable the error source entirely, so I do not know what to expect in terms of performance gains.

[WHEA-Disable.zip](https://github.com/mann1x/WHEAService/files/7574621/WHEA-Disable.zip)
(This disables WHEA 19 and 20s)

Use at your own discretion.

Also, if someone could perform some tests, and create a performance metric, that would be particularly helpful.

**Comment by mann1x** [comment]
Thanks!
Didn't know this way, it's very safe and non destructive.
I'll check it out and try to "benchmark" it.

My guess is the event creation has the biggest hit on load.
Even if the WMI processing it's still on for sure it's better.
And it solves the other big issue which is the massive amount of WHEAs wiping out the other events in the System log.

**Comment by mann1x** [comment]
BTW I wouldn't disable Event 20, it's something that needs to be addressed.
Not the same as the flood of Event 19.

**Comment by hahagu** [comment]
It's under event log's 'information' section, so I thought it'd be safe.
What is it anyways?

**Comment by hahagu** [comment]
Also, if the registry tweak somehow doesn't work,
Check GUID of WHEA Error at Event logger,
open regedit and go to
`[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\WMI\Autologger\EventLog-System\{INSERT_THAT_GUID_HERE}`
and set enabled to 0

**Comment by mann1x** [comment]
Not sure on Ryzen what is the exact error for Event 20 but on the old AMD CPUs was described as: HyperTransport Watchdog Timeout Error.
It's a fatal error and usually leads to a BSOD or a reboot.

**Comment by hahagu** [comment]
It's just logged as 'WHEA-Event' and nothing else.
Also, there hasn't been any crashes since I've suppressed it, so I am supposing that it is not, at least, a fatal error.

**Comment by mann1x** [comment]
Very weird... this is the description for Event 18:

A fatal hardware error has occurred.

Reported by component: Processor Core
Error Source: Machine Check Exception
Error Type: Cache Hierarchy Error
Processor APIC ID: 2

The details view of this entry contains further information.

Event 20 should be something like this:

A fatal hardware error has occurred.

Component: AMD Northbridge
Error Source: Machine Check Exception
Error Type: CRC Error
Processor ID: 0

The details view of this entry contains further information.

Maybe the flood of Event 19 was causing a cascade instability effect.

**Comment by hahagu** [comment]
Do you have discord?
Maybe we can chat over there,
since it'd be more efficient.

hahagu#1884
